Development
BenjaminGarza/Backgrounds-and-Gradients pull request #1
Opened 2019-07-17 22:40 UTC by BenjaminGarza

2019-07-18 19:50 UTC, Oghenebrume50 commented
Great start to this project. But some few changes need to be made

2019-07-18 19:56 UTC, Oghenebrume50 requested changes
Fix those things and submit for re-review, nice attempt, you did really good.

2019-07-18 19:56 UTC, Oghenebrume50 commented on main.css
> +  height:  805px;
This line is affecting your code, the footer jumps up. You may want to look into heights and width, most times you don't need to explicitly set heights of a large container. and your width is off too, it leaves a big space that is scrollable, too big to be ignored.

2019-07-18 19:56 UTC, Oghenebrume50 commented on index.html
> +       <article id="billboard">
This article tag shouldn't be wrapping the nav tag.

2019-07-18 19:56 UTC, Oghenebrume50 commented on index.html
> +        <aside>
The content in this aside tag should be in the footer, and the images should be passed as background images, just like you did for the ones above. use a div and pass as background image

2019-07-25 17:31 UTC, Oghenebrume50 commented
reviewing

2019-07-25 17:54 UTC, Oghenebrume50 requested changes

2019-07-25 17:54 UTC, Oghenebrume50 commented on main.css
>      margin: 60px;
If you remove this margin you would see how it affects the page display. You have to be careful with margins

2019-07-25 17:54 UTC, Oghenebrume50 commented on main.css
> +    width:1440px;
You shouldn't set an explicit width like this on the body.

2019-08-09 20:43 UTC, samgaco commented
Hi, @BenjaminGarza I can't see any changes after the last review. Is everything ok?. I wait for your reply.

2019-08-09 22:38 UTC, BenjaminGarza commented
> Hi, @BenjaminGarza I can't see any changes after the last review. Is everything ok?. I wait for your reply.

Just made more changes today and putting in for another code review, thanks!

2019-08-10 01:31 UTC, bolah2009 commented
Currently under review

2019-08-10 01:41 UTC, bolah2009 approved these changes
## Nice Job [Ben](../../)  :clap: 

The [clone](https://raw.githack.com/BenjaminGarza/Backgrounds-and-Gradients/Development/index.html) looks good to me. :+1:

#### Consider checking these [errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Fraw.githack.com%2FBenjaminGarza%2FBackgrounds-and-Gradients%2FDevelopment%2Findex.html) before merging.

#### Friendly reminder: You should use Github Flow and [Linter](https://github.com/microverseinc/linters-config#linters-config) in this project. However, changing it now would take too much time. Please make sure you use Github Flow and [Linter](https://github.com/microverseinc/linters-config#linters-config) in the next project. You will find instructions in the Pathwright lesson description.

Good luck with your next project.

Cheers
[Bola](https://bolabuari.com/)

2019-08-12 03:52 UTC, merged